In [2]:
import myapp

In [5]:
myapp.view_app()

[{'name': 'Owais Ali Arshad', 'fname': 'Arshad ali', 'email': 'owais@.com', 'age': 18, 'adress': 'Karachi, Sindh, Pakistan', 'education': 'Intermediate', 'school': 'Islamia govt science collage'}, {'name': 'Uzair Ali Arshad', 'fname': 'Arshad ali', 'email': 'uzair.com', 'age': 17, 'adress': 'Karachi, Sindh, Pakistan', 'education': 'Matric', 'school': 'Iqra High School'}, {'name': 'Usaid Ullah Arshad', 'fname': 'Arshad ali', 'email': 'usaid.com', 'age': 12, 'adress': 'Karachi, Sindh, Pakistan', 'education': 'Primary', 'school': 'Native School'}, {'name': 'Humaid Ullah Arshad', 'fname': 'Arshad ali', 'email': 'Humaid.com', 'age': 7, 'adress': 'Karachi, Sindh, Pakistan', 'education': 'KG', 'school': 'Usman Public School'}]


In [6]:
myapp.send_app()

In [2]:
import numpy as np

# Task no 1
def function1():
    # create 2d array from 1,12 range 
    # dimension should be 6row 2 columns  
    # and assign this array values in x values in x variable
    # Hint: you can use arange and reshape numpy methods  
    x =  np.arange(1,13).reshape((6,2))
    return x
function1()

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [106]:
def function2():
    #create 3D array (3,3,3)
    #must data type should have float64
    #array value should be satart from 10 and end with 36 (both included)
    # Hint: dtype, reshape 
    
    x = np.arange(10,37,dtype=np.float64).reshape((3,3,3))     #wrtie your code here

    return x
function2()

array([[[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]],

       [[19., 20., 21.],
        [22., 23., 24.],
        [25., 26., 27.]],

       [[28., 29., 30.],
        [31., 32., 33.],
        [34., 35., 36.]]])

In [113]:
def function3():
    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1, 100*10+1).reshape((100,10))
    value_1=np.where(a%5==0)
    a=a[value_1]
    value_2=np.where(a%7==0)
    x = a[value_2] #wrtie your code here
    return print(x)
function3()

[ 35  70 105 140 175 210 245 280 315 350 385 420 455 490 525 560 595 630
 665 700 735 770 805 840 875 910 945 980]


In [117]:
def function4():
    #Swap columns 1 and 2 in the array arr.
   
    arr = np.arange(9).reshape(3,3)
  
    return arr[:,[1,0]]
    
function4()

array([[1, 0],
       [4, 3],
       [7, 6]])

In [119]:
def function6():
    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively
   
    arr = np.zeros(10) #wrtie your code here
    arr[4]=10
    arr[7]=20
    return arr
function6()

array([ 0.,  0.,  0.,  0., 10.,  0.,  0., 20.,  0.,  0.])

In [121]:
def function8():
    # Create a new array of 2x5 uints, filled with 6.
    
    x =np.zeros((2,5))
    x[:]=6 #write your code here
  
    return x
function8()

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [124]:
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.
    
    a =np.arange(2,100,step=2) # write your code here
  
    return a
function9()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [140]:
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt =arr-np.vstack(brr) # write your code here 
  
    return subt
function10()

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [148]:
def function11():
    # Replace all odd numbers in arr with -1 without changing arr.
    
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    ans=arr[1::2]=-1 #write your code here 
  
    return ans
function11()

-1

In [150]:
def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
    arr = np.array([1,2,3])
    ans = np.hstack((np.repeat(arr,3),arr,arr,arr)) #write your code here 
  
    return ans
function12()

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [155]:
def function13():
    # Set a condition which gets all items between 5 and 10 from arr.
    
    
    arr = np.array([2, 6, 1, 9, 10, 3, 27])
    ans =arr[(arr>5)&(arr<10)] #write your code here 
  
    return ans
function13()

array([6, 9])

In [156]:
def function14():
    # Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method
    
    
    arr = np.arange(10, 34,1).reshape(8,3) #write reshape code
    ans = np.split(arr,4) #write your code here 
  
    return ans
function14()

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [163]:
def function15():
    #Sort following NumPy array by the second column
    
    
    arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
    arr[:,1]=np.sort(arr[:,1]) #write your code here 
    ans=arr
    return ans
function15()


array([[ 8,  1, -2],
       [-4,  2,  7],
       [ 6,  3,  9]])

In [3]:
x = np.array([[1], [2], [3]])
y = np.array([[2], [3], [4]])
ans =np.hstack((x,y)) #write your code here 

ans

array([[1, 2],
       [2, 3],
       [3, 4]])

In [168]:
arr = np.arange(1,10*10+1).reshape((10,10))
np.where((arr%3==0)&(arr%5==0),"YES",'NO')   

array([['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']],
      dtype='<U3')

In [3]:

def recursionn(k):
    if k>=0:
        k=k-1
        recursionn(k)
        print('k', k)
    elif k>=0 and k<=1:
        k=k+1
        print(k)
    else:
        return(k)
    


In [5]:
recursionn(0.5)

k -0.5
