# Numpy_Assignment_2::

In [1]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
array=np.arange(0,10)
array.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [3]:
array_1=np.arange(0,10).reshape(2,5)
array_2=np.ones((2,5))
stack_array=np.vstack((array_1,array_2))
stack_array

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [4]:
arr_1=np.array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1])
arr_2=np.array([5, 6, 7, 8, 9, 1, 1, 1, 1, 1])
np.concatenate((arr_1,arr_2),axis=0)

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [5]:
print(stack_array)
print(np.ravel(stack_array))

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [8]:
arr=np.arange(3,15).reshape(3,2,2)
arr.reshape(12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [10]:
Array=np.random.randn(40)
Array.reshape(4,2,5)

array([[[-0.07855219,  0.26162111, -1.10817693,  0.01981324,
         -0.46988718],
        [-0.02076818, -0.6830072 ,  0.50695078, -0.97761374,
         -0.48074979]],

       [[-0.80521187,  0.68843225, -1.07523354, -0.09278273,
          1.07851639],
        [-0.97916001,  0.16347144, -1.89872937,  0.04209333,
          1.80869605]],

       [[-0.56594938,  1.17296531,  0.61593925, -0.59643907,
          0.83477738],
        [-1.05977177, -0.82839717, -1.07693286, -0.61580753,
         -0.30635089]],

       [[-0.07375554, -0.29378856, -0.93028062, -0.44579073,
          0.03204862],
        [-0.77825945, -0.72900177, -0.00205994, -0.1856906 ,
         -0.04696035]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [13]:
_5x5_=np.empty((5,5))
np.square(_5x5_)

array([[4.67296746e-307, 1.69121096e-306, 7.56605919e-307,
        7.56587585e-307, 1.37961302e-306],
       [1.05699242e-307, 8.01097889e-307, 1.78020169e-306,
        7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.33511018e-306,
        6.23057689e-307, 1.33511290e-306],
       [1.78019082e-306, 8.45559303e-307, 8.06613040e-308,
        6.89810244e-307, 1.22387550e-307],
       [2.22522596e-306, 8.34423917e-308, 1.11261162e-306,
        1.78021527e-306, 3.75597400e-317]])

## Question:8

### Create 5x6 an array and find the mean?

In [21]:
_5x6_=np.random.randn(5,6)
_5x6_.mean()

0.2785611071334286

## Question:9

### Find the standard deviation of the previous array in Q8?

In [22]:
_5x6_.std()

0.932695556725632

## Question:10

### Find the median of the previous array in Q8?

In [23]:
np.median(_5x6_)

0.42887048430638514

## Question:11

### Find the transpose of the previous array in Q8?

In [24]:
np.transpose(_5x6_)

array([[ 1.17393281,  0.98589208, -0.1777639 , -0.58314935, -0.65020191],
       [ 0.96426404, -0.84845002,  0.42294402,  1.18300014,  0.79182211],
       [ 0.43479695,  0.82403009,  0.73985314, -1.91916648,  1.54662916],
       [-0.64602528,  0.65515178, -0.31280145,  0.15397805,  1.10879969],
       [-0.80989678, -0.07311696,  0.14096551,  2.13296763,  1.60396086],
       [-0.95194295,  0.55564277,  1.25530143, -1.01843045, -0.3261535 ]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [30]:
_4x4_=np.random.randn(4,4)
print(np.sum(np.diagonal(_4x4_)))


-2.6495566981959495


## Question:13

### Find the determinant of the previous array in Q12?

In [31]:
np.linalg.det(_4x4_)

2.2340066215097014

## Question:14

### Find the 5th and 95th percentile of an array?

In [35]:
print(np.percentile(_4x4_,5))
print(np.percentile(_4x4_,95))

-1.2456052718686819
1.1926828600444481


## Question:15

### How to find if a given array has any null values?

In [36]:
ARR=np.arange(0,10)
np.any(ARR==0)

True