Import the numpy package under the name np

In [1]:
import numpy as np

Create a null vector of size 10

In [2]:
print(np.zeros((10)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49


In [3]:
array=np.arange(10,50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Find the shape of previous array in question 3


In [4]:
print(np.shape(array))

(40,)


Print the type of the previous array in question 3

In [5]:
array.dtype

dtype('int32')

Print the numpy version and the configuration


In [6]:
print(np.__version__, np.__config__)

1.19.2 <module 'numpy.__config__' from 'C:\\Users\\owais\\anaconda3\\lib\\site-packages\\numpy\\__config__.py'>


Print the dimension of the array in question 3

In [7]:
print(np.ndim(array))

1


Create a boolean array with all the True values


In [8]:
bool_array=array>=10
print(bool_array)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


Create a two dimensional array


In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a three dimensional array


In [10]:
empty_array=np.empty((2,3,4))
print(empty_array)

[[[6.89274836e-312 7.50979782e-322 0.00000000e+000 0.00000000e+000]
  [1.37961302e-306 1.16096346e-028 1.04857803e-142 1.16467185e-028]
  [1.28223029e-153 2.72829434e-057 4.58774487e-072 1.87889758e-153]]

 [[6.72321459e-067 3.00517840e-067 1.73002210e-153 1.65174261e-076]
  [1.96852601e-062 1.96947557e-062 1.73031344e-153 1.73810430e-076]
  [1.29009442e-057 1.58143796e-153 5.91445349e-038 5.88568417e+294]]]


# Difficulty Level Easy


Reverse a vector (first element becomes last)


In [11]:
reverse_array=empty_array[::-1]
print(reverse_array)

[[[6.72321459e-067 3.00517840e-067 1.73002210e-153 1.65174261e-076]
  [1.96852601e-062 1.96947557e-062 1.73031344e-153 1.73810430e-076]
  [1.29009442e-057 1.58143796e-153 5.91445349e-038 5.88568417e+294]]

 [[6.89274836e-312 7.50979782e-322 0.00000000e+000 0.00000000e+000]
  [1.37961302e-306 1.16096346e-028 1.04857803e-142 1.16467185e-028]
  [1.28223029e-153 2.72829434e-057 4.58774487e-072 1.87889758e-153]]]


Create a null vector of size 10 but the fifth value which is 1


In [12]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a 3x3 identity matrix


In [266]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
arr = np.array([1, 2, 3, 4, 5])
#Convert the data type of the given array from int to float
arr.astype('float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [15]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
#Multiply arr1 with arr2

arr1*arr2


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [16]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
#Make an array by comparing both the arrays provided above
np.maximum(arr1,arr2)

array([[ 1.,  4.,  3.],
       [ 7.,  5., 12.]])

In [17]:
#Extract all odd numbers from arr with values(0-9)
nparray=np.arange(0,10)
print(nparray[1::2])


[1 3 5 7 9]


In [18]:
#Replace all odd numbers to -1 from previous array
nparray[1::2]=-1
nparray

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
arr = np.arange(10)
#Replace the values of indexes 5,6,7 and 8 to 12
arr[[5,6,7,8]]=12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


In [20]:
#Create a 2d array with 1 on the border and 0 inside
square=np.ones((3,3))
square[1,1]=0
square

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

In [21]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
#Replace the value 5 to 12

arr2d[1][1]=12
print(arr2d)


[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
#Convert all the values of 1st array to 64
arr3d[0]=64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


In [36]:
#Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
arr_2d=np.arange(0,10)
arr_2d=arr_2d.reshape(2,5)
print(arr_2d[0][:])

[0 1 2 3 4]


In [38]:
#Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
print(arr_2d[1][1])

6


In [58]:
#Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
print(arr_2d[:2,2])

[2 7]


In [65]:
#Create a 10x10 array with random values and find the minimum and maximum values
random_array=np.random.random(size=10*10)
print(np.max(random_array),np.min(random_array))

0.9899598002583637 0.02142780882508777


In [80]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Find the common items between a and b
print(np.intersect1d(a,b))

[2 4]


In [85]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Find the positions where elements of a and b match
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


In [131]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
#Find all the values from array data where the values from array names are not equal to Will and Joe
joe=(np.where(names!='Joe'))
will=np.where(names!='Will')
where=np.intersect1d(joe,will)
data[where]

array([[-0.88587687, -0.33973277, -0.4745706 , -0.74746139],
       [-1.34350823, -1.03279716,  1.40661184, -0.20311626]])

# Difficulty Level Hard


In [144]:
#Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
_5x3_=np.arange(1,16)
_5x3_.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [145]:
#Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
_2x2x4_=np.arange(1,17)
_2x2x4_.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [168]:
#Swap axes of the array you created in Question 32
a=np.swapaxes(_2x2x4_,0,0)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [188]:
#Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
aRr=np.arange(0.2,10)
sqrt=np.sqrt(aRr)
less=np.where(sqrt<0.5)
sqrt[less]=0
print(sqrt)

[0.         1.09544512 1.4832397  1.78885438 2.04939015 2.28035085
 2.48997992 2.68328157 2.86356421 3.03315018]


In [194]:
#Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
arr_1=np.random.randn(12)
arr_2=np.random.randn(12)
max_array=np.maximum(arr_1,arr_2)
print(max_array)

[ 0.70040323  1.09596314  0.16696475  0.27956636  0.56740568  0.05657396
 -0.16083091 -0.28288451  1.47288013  2.21363237  0.57590078  0.32620061]


In [200]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
#Find the unique names and sort them out!
print(np.unique(names))

['Bob' 'Joe' 'Will']


In [224]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
#From array a remove all items present in array b
same=np.where(a==np.intersect1d(a,b))
print(np.delete(a,same))


[1 2 3 4]


In [259]:
#Following is the input NumPy array delete column two and insert following new column in its place.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray=np.insert(sampleArray,1,newColumn,axis=1)
sampleArray=np.delete(sampleArray,2,axis=1)
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [261]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
#Find the dot product of the above two matrix
print(np.dot(x,y))

[[ 28.  64.]
 [ 67. 181.]]


In [265]:
#Generate a matrix of 20 random values and find its cumulative sum
random_array=np.random.randn(20)
print(np.cumsum(random_array))

[1.20171959 2.78237651 3.82683384 3.49954889 5.16265647 6.3087904
 6.35350224 6.96806352 7.24279845 8.6610774  6.77423983 4.55014679
 6.30574536 6.71387372 6.93022221 6.3732244  6.02748118 6.38155115
 7.73385047 8.15469166]
